### PR TITLE
Use Documenter.jl for documentation

### LINKED ISSUE #9: Use Documenter.jl for the documentation
We should use https://github.com/JuliaDocs/Documenter.jl for the documentation

### PR DESCRIPTION
**Pull request by abhishalya**
This uses the Documenter.jl instead of readthedocs
to generate documentation.

Closes https://github.com/JuliaDSP/Deconvolution.jl/issues/9

### CODE REVIEW

**Comment by abhishalya** [comment]
Please review @giordano

**Comment by jakubwro** [comment]
I generated docs on my machine, everything works fine

**Comment by giordano** [comment]
@jakubwro This is my fault that I didn't finish to review #8 before (I've been out of town until a couple of days ago), but for the sake of having a speedy review of this PR for Google Code in, would you mind if I'll review and hopefully merge this one first (targeting later today) and then yours?  You'll need to update the documentation, but I can take care of it if that's too much of a hassle for you.

**Comment by jakubwro** [comment]
> @jakubwro This is my fault that I didn't finish to review #8 before (I've been out of town until a couple of days ago), but for the sake of having a speedy review of this PR for Google Code in, would you mind if I'll review and hopefully merge this one first (targeting later today) and then yours? You'll need to update the documentation, but I can take care of it if that's too much of a hassle for you.

It's not a big deal, please merge #10 and I will resolve conflicts on my branch

**Review by giordano — APPROVED** [review]

**Comment by giordano** [comment]
Thank you very much!

**Pull request merged**
