### PR TITLE
Changing doc structure

### PR DESCRIPTION
**Pull request by jakubwro**
1. I suggest to create sub folders for each method in doc/src.
2. White frames in jpg do not look good in dark theme, markdown tables seem to be better.
3. I cannot run doc/src/wiener/time-series.jl. I understand that I need older version of Julia to run that, I think it is better to upgrade LombScargle.jl to support the newest environment. If you agree I can contribute there.

```
(v1.2) pkg> add LombScargle
  Updating registry at `~/.julia/registries/General`
  Updating git-repo `https://github.com/JuliaRegistries/General.git`
 Resolving package versions...
ERROR: Unsatisfiable requirements detected for package LombScargle [fc60dff9]:
 LombScargle [fc60dff9] log:
 ├─possible versions are: 0.4.0 or uninstalled
 ├─restricted to versions * by an explicit requirement, leaving only versions 0.4.0
 └─restricted by compatibility requirements with FFTW [7a1cc6ca] to versions: uninstalled — no versions left
   └─FFTW [7a1cc6ca] log:
     ├─possible versions are: [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0] or uninstalled
     ├─restricted to versions [0.0.0-0.0, 0.1.0-0.1, 0.2.0-0.2, 0.3.0-0.3, 1.0.0-1] by Deconvolution [41ba435c], leaving only versions [0.1.0-0.1.2, 0.2.0-0.2.4, 0.3.0, 1.0.0-1.0.1, 1.1.0]
     │ └─Deconvolution [41ba435c] log:
     │   ├─possible versions are: 0.3.0 or uninstalled
     │   └─Deconvolution [41ba435c] is fixed to version 0.3.0
     └─restricted to versions 1.1.0 by an explicit requirement, leaving only versions 1.1.0
```

### CODE REVIEW

**Comment by jakubwro** [comment]
@giordano after executing line below I was able to run the script. Some changes were required to make it work, please see the last commit.
```
(v1.2) pkg> dev https://github.com/JuliaAstro/LombScargle.jl
```

**Comment by giordano** [comment]
Thanks for taking care of this!  I'm updating LombScargle so that it can be properly installed, it didn't have a Project.toml

**Comment by jakubwro** [comment]
> Thanks for taking care of this! I'm updating LombScargle so that it can be properly installed, it didn't have a Project.toml

I needed to do something simple after working whole weekend on this NTT stuff without much progress :)

**Comment by giordano** [comment]
Ok, `LombScargle` should now be installable

**Comment by jakubwro** [comment]
> Ok, `LombScargle` should now be installable

I confirm, it woks with "add" after updating General registry. Anyway generated plots are slightly different, I think caused by changes in Plots.jl

**Pull request merged**
